name: CI Pipe

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 18

        - name: Install Dependencies 
          run: npm install

        - name: Run Tests
          run: npm test
